# Generated by Django 4.2.5 on 2023-11-19 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_start', models.DateTimeField(verbose_name='Время проведения')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
                ('price', models.FloatField(default=0, verbose_name='Цена билета')),
                ('count_tickets', models.PositiveIntegerField(default=0, verbose_name='Количество билетов')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятие',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество билетов')),
                ('total_price', models.FloatField(verbose_name='Общая стоимость')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.CreateModel(
            name='EventCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_event_starts', models.DateTimeField(verbose_name='Дата создания')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество билетов')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_creations', to='events.event', verbose_name='Мероприятие')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_prices', to='events.event', verbose_name='Стоимость билета')),
            ],
            options={
                'verbose_name': 'Созданное организатором мероприятие',
                'verbose_name_plural': 'Созданные организаторами мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EditedEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество добавленных билетов')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_event', to='events.event', verbose_name='Мероприятие')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_event_prices', to='events.event', verbose_name='Новая стоимость билета')),
            ],
        ),
    ]
