# Generated by Django 4.2.5 on 2023-12-19 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='eventcreation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='eventcreation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_creations', to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='eventcreation',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_prices', to='events.event', verbose_name='Стоимость билета'),
        ),
        migrations.AddField(
            model_name='event',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.category', verbose_name='Категории'),
        ),
    ]
