# Generated by Django 4.2.5 on 2023-11-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcreation',
            name='created_event_starts',
        ),
    ]
