# Generated by Django 4.2.5 on 2023-11-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventcreation_created_event_starts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
